# Generated by Django 4.2.3 on 2023-07-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='arte_marcial',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
